"""Prompt templates for DocGemma."""

from .templates import (
    EMERGENCY_CLASSIFICATION,
    EMERGENCY_RESPONSE,
    EXPERT_RESPONSE,
    PATIENT_RESPONSE,
    USER_TYPE_CLASSIFICATION,
)

__all__ = [
    "EMERGENCY_CLASSIFICATION",
    "EMERGENCY_RESPONSE",
    "EXPERT_RESPONSE",
    "PATIENT_RESPONSE",
    "USER_TYPE_CLASSIFICATION",
]
